### ISSUE TITLE
Sink selflog throwing Input string was not in a correct format

### ISSUE THREAD

**Issue by GauravSharmaDA** [serilog/serilog-sinks-elasticsearch#155]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X ] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.1.0

**What is the target framework and operating system? See [target frameworks]
- [ X] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
Trying to log information and getting this exception:

**_2018-02-14T13:18:57.3689724Z Caught exception while preforming bulk operation to Elasticsearch:_** System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.<>c__DisplayClass22_0.<.ctor>b__0(LogEvent event, DateTimeOffset offset)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.GetIndexForEvent(LogEvent e, DateTimeOffset offset)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)

**Please describe the expected behavior?**
I am expecting it to log.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

Here's the code

                var serilogger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Elasticsearch(new Serilog.Sinks.Elasticsearch.ElasticsearchSinkOptions(
                                new Uri("http://localhost:9200/"))
                                {
                                    AutoRegisterTemplate = false,
                                    IndexFormat = "DCExperiment-{0.yyyy.MM}",
                                    BatchPostingLimit = 50,
                                    CustomFormatter = new ExceptionAsObjectJsonFormatter(renderMessage: true)
                                })
                .CreateLogger();
            serilogger.Information("Logger Setup done.");

**Comment by mivano** [comment]
Can you try to use {0:yyyy.MM} ? So a : instead of a . (dot) in your indexFormat.

**Comment by GauravSharmaDA** [comment]
**Thanks a ton Mivano. It helped.**

but I got below error straight way. Busy searching. If you remember on top of your head what I am doing, please let me know.

2018-02-15T05:05:49.3639778Z   ---> 
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Connection\HttpConnection-CoreFx.cs:line 73
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 196
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 180
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 97
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\ElasticLowLevelClient.Generated.cs:line 26
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)

**Comment by mivano** [comment]
Sorry, does not ring a bell. Those async stack traces are tricky. Did you found out the issue?

**Comment by Rwing** [comment]
I think the IndexFormat only allow low-case letters

**Comment by mivano** [comment]
@Rwing that is correct. Will force it the future to be lowercase anyway.
