### ISSUE TITLE
Serilog Elasticsearch throwing error when application hosted in Docker

### ISSUE THREAD

**Issue by bikashbehuria** [serilog/serilog-sinks-elasticsearch#171]
**A few questions before you begin:**

>  [sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks)   code project, 
 
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
6.5.0

**What is the target framework and operating system? See [target frameworks]
- [x] netCore 2.0

**Please describe the current behavior?**
Serilog Elasticsearch sink works well when running from Visual Studio but getting error when running the same application Docker Linux container. When I debugged by adding SelfLog , seems like the request is not reaching to Elasticsearch and thorws exception. The same application works fine from windows host.

**Please describe the expected behavior?**
The application should work fine with both Windows and Docker linux host

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
Not sure if it is a bug or some problem with my settings , any hint will help me.

I did some sample connecting elasticsearch directly using Elasticsearch.net library , found the error is being thrown from Elasticsearch library so this might not be a serilog sink issue

**Comment by mivano** [comment]
A bit difficult to troubleshoot, but you need to explicitly enable ports between containers. Is your ES instance also running in a docker container?

**Comment by provanguard** [comment]
We are having possibly the same issue. Serilog Elasticsearch sink works well when running from Visual Studio but getting error when running the same application in Azure Web Apps for container, meaning a Docker Linux container. The error observed:

`2018-09-06T17:02:51.600083189Z 2018-09-06T17:02:51.5996368Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: One or more errors occurred. (Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.) ---> System.AggregateException: One or more errors occurred. (Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.) ---> Elasticsearch.Net.PipelineException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.
2018-09-06T17:02:51.600179389Z    at Elasticsearch.Net.RequestPipeline.ThrowBadAuthPipelineExceptionWhenNeeded(IApiCallDetails details, IElasticsearchResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 320
2018-09-06T17:02:51.600229789Z    at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 443
2018-09-06T17:02:51.600302790Z    at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 68
2018-09-06T17:02:51.600311490Z    --- End of inner exception stack trace ---
2018-09-06T17:02:51.600317990Z    --- End of inner exception stack trace ---
2018-09-06T17:02:51.600370390Z    at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 196
2018-09-06T17:02:51.600434990Z    at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 180
2018-09-06T17:02:51.600482090Z    at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters) in c:\Projects\elastic\net-master\src\Elasticsearch.Net\Transport\Transport.cs:line 97
2018-09-06T17:02:51.600497590Z    at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
2018-09-06T17:02:51.600511690Z    at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)`

Net Core 2.1, latest runtime.  Here is our Azure Application settings that the code loads:

`XXX_Serilog__WriteTo__Elasticsearch__Name
Elasticsearch

XXX_Serilog__WriteTo__Elasticsearch__Args__nodeUris
https://xxx.us-east-1.aws.found.io:9243/

XXX_Serilog__WriteTo__Elasticsearch__Args__indexFormat
xxx-api-dev

XXX_Serilog__WriteTo__Elasticsearch__Args__connectionGlobalHeaders
Authorization=Basic base64encodedcredentials`

Other apps in the normal Azure Web apps (Windows based IIS) run ok with identical settings.

**Comment by NeophileJagpal** [comment]
We are also having same issue. Able to Run dotnet core 2.2 application in VS2019 but when running in Linux using docker-image getting same error `Caught exception while preforming bulk operation to Elasticsearch`

we are not using any authentication to connecting elastic search.

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.

**Comment by pantonis** [comment]
@mivano I am getting this:

```
2020-02-20T13:39:47.8467752Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: An error occurred while sending the request.. Call: Status code unknown from: POST /_bulk
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)
2020-02-20T13:39:50.0903909Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: An error occurred while sending the request.. Call: Status code unknown from: POST /_bulk
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)
```

using the following packages:
```
<PackageReference Include="Serilog" Version="2.9.0" />
<PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
<PackageReference Include="Serilog.Sinks.ElasticSearch" Version="8.0.1" />
<PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
```

**Comment by mivano** [comment]
Can you see something on your server end? Log entry indicating why it does not return anything? Looks like it is in the underlying Elasticsearch.Net library. So if you can reproduce it using this library alone with similar call and endpoint, you might be able to eliminate some elements and check with elastic github page themselves.

**Comment by pantonis** [comment]
@mivano I had wrong url. The server is using SSL and I had ```http://``` on my url. Error message though was not helpful at all!

**Comment by mivano** [comment]
Ah so it could not do the handshake at all. Good to hear it is fixed now.
