### ISSUE TITLE
ES errors lead to infinite loop

### ISSUE THREAD

**Issue by jasper-d** [serilog/serilog-sinks-elasticsearch#237]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
- Serilog.Sinks.ElasticSearch 7.1.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netcoreapp2.2, Windows x64

**Please describe the current behavior?**
We encountered a mapping error because of a non-unique property name which gets reported in the self log like this:

````
2019-04-23T14:42:50.3120513Z Received failed ElasticSearch shipping result 400: {"type":"mapper_parsing_exception","reason":"object mapping for [fields.StreamIdentity] tried to parse field [StreamIdentity] as object, but found a concrete value"}. Failed payload : {"@timestamp":"2019-04-21T20:59:18.5646467+00:00","level":"Warning","messageTemplate":"Forcing match end {StreamIdentity}. Last data received {LastUpdatedUtc} UTC, now {Now} UTC.","message":"Forcing match end \"Match ID 154343 - Stream Type Delayed (2)\". Last data received 04/21/2019 17:57:29 UTC, now 04/21/2019 20:59:18 UTC.","fields":{"StreamIdentity":"Match ID 154343 - Stream Type Delayed (2)","LastUpdatedUtc":"2019-04-21T17:57:29.1892851Z","Now":"2019-04-21T20:59:18.5633281Z","SourceContext":"My.Namespace.CalculationService.DataManagement.Analyzer","ThreadId":22,"MachineName":"hostname42","AppName":"My.Namespace.CalculationService"}}.
2019-04-23T14:42:50.3122709Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogClient: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Serilog.Debugging.SelfLog.WriteLine(String format, Object arg0, Object arg1, Object arg2)
   at My.Namespace.Infrastructure.Logging.LogConfiguration.WriteElasticErrorToSelfLog(String logRow, Nullable`1 esStatus, String errorMessage) in W:\_work\4\s\My.Namespace.Infrastructure\Logging\LogConfiguration.cs:line 148
   at CallSite.Target(Closure , CallSite , Func`4 , String , Nullable`1 , Object )
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogClient.GetInvalidPayloadAsync(DynamicResponse baseResult, List`1 payload, List`1& cleanPayload)
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogClient.SendPayloadAsync(List`1 payload, Boolean first)
````
These errors are logged continuously in the self log, apparently with some backoff (i.e. the time between errors increases).

The offending line is the warning in this buffer file:

````
{"@timestamp":"2019-04-21T20:59:18.5646467+00:00","level":"Warning","messageTemplate":"Forcing match end {StreamIdentity}. Last data received {LastUpdatedUtc} UTC, now {Now} UTC.","message":"Forcing match end \"Match ID 154343 - Stream Type Delayed (2)\". Last data received 04/21/2019 17:57:29 UTC, now 04/21/2019 20:59:18 UTC.","fields":{"StreamIdentity":"Match ID 154343 - Stream Type Delayed (2)","LastUpdatedUtc":"2019-04-21T17:57:29.1892851Z","Now":"2019-04-21T20:59:18.5633281Z","SourceContext":"My.Namespace.CalculationService.DataManagement.Analyzer","ThreadId":22,"MachineName":"hostname42","AppName":"My.Namespace.CalculationService"}}
{"@timestamp":"2019-04-21T20:59:18.5678482+00:00","level":"Information","messageTemplate":"Calculation finished. Fire OnCalculationCompleted event for match {@StreamIdentity}","message":"Calculation finished. Fire OnCalculationCompleted event for match StreamIdentity { MatchId: 154343, StreamType: Delayed }","fields":{"StreamIdentity":{"_typeTag":"StreamIdentity","MatchId":154343,"StreamType":"Delayed"},"SourceContext":"My.Namespace.Calculation.Core.Calculators.Calculator","ThreadId":15,"MachineName":"hostname42","AppName":"My.Namespace.CalculationService"}}
{"@timestamp":"2019-04-21T20:59:18.5705604+00:00","level":"Information","messageTemplate":"Serialized data ({PayloadLength:F2} kb) for message with key '{Subject}'.","message":"Serialized data (45.00 kb) for message with key '\"STATISTIC.FINALRESULT.154343.DELAYED.173828\"'.","fields":{"PayloadLength":45,"Subject":"STATISTIC.FINALRESULT.154343.DELAYED.173828","SourceContext":"My.Namespace.Infrastructure.Nats.NatsSender","ThreadId":15,"MachineName":"hostname42","AppName":"My.Namespace.CalculationService"},"renderings":{"PayloadLength":[{"Format":"F2","Rendering":"45.00"}]}}
{"@timestamp":"2019-04-21T20:59:18.5708365+00:00","level":"Information","messageTemplate":"Discard producer for match {@StreamIdentity}","message":"Discard producer for match StreamIdentity { MatchId: 154343, StreamType: Delayed }","fields":{"StreamIdentity":{"_typeTag":"StreamIdentity","MatchId":154343,"StreamType":"Delayed"},"SourceContext":"My.Namespace.CalculationService.EventHandler","ThreadId":15,"MachineName":"hostname42","AppName":"My.Namespace.CalculationService"}}
EOF
````

So far everything looks fine. However, the three info messages in the buffer are stored in ES every time the sink tries to send the logs to ES.
Since the bookmark file is not updated (probably because of the error ES returns) and still points to the warning in the buffer file, we effectively have an infinite loop.
Logs stored in subsequent buffer files are not persisted in ES. I assume the previous buffer must be completely transmitted before the next buffer file is processed.

Our ES sink config looks like this:

````
private static LoggerConfiguration SetupElasticSink(this LoggerConfiguration loggerConfig, IConfig applicationConfig, string logSubDir)
{
    const string fileName = "serilog-es.buffer";
    var bufferFileName = GetLogFileName(applicationConfig.LogDirectory, logSubDir, fileName);

    return loggerConfig.WriteTo.Elasticsearch(
        new ElasticsearchSinkOptions(applicationConfig.ElasticNodes)
        {
            AutoRegisterTemplate = true,
            AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
            IndexFormat = GetElasticIndexName(applicationConfig.CurrentEnvironment),
            FormatProvider = CultureInfo.InvariantCulture,
            EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog,
            MinimumLogEventLevel = LogEventLevel.Information,
            BufferBaseFilename = bufferFileName,
            BufferFileSizeLimitBytes = 1024 * 1024 * 200, // 200 MB
            BufferLogShippingInterval = TimeSpan.FromSeconds(2),
            BufferCleanPayload = WriteElasticErrorToSelfLog,
        });
}
```` 

**Please describe the expected behavior?**
An erroneous log message should not effectively stop the ES sink from storing later log messages (i.e. messages from subsequent buffers). It should also not lead to dupes in ES.

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
Will do so if necessary.

**Comment by mivano** [comment]
The error you see is Elasticsearch telling you that you first try to index a field named `StreamIdentity` as an object, however in the same index (so same day) you already indexed data as a concrete type in the same field.

for example:

```csharp
Log.Information("this is a string {a}", "stringvalue");
Log.Information("this is an object {a}", new { b: 3, c: true});
```
The first time a field gets indexed, it analyses the type and will keep using this for the duration of the index.

So make sure you use unique names for your fields.

**Comment by mivano** [comment]
And yes, you are right, it should not blow up indeed. The buffer option is not that efficient when handling errors. Open for a PR, unfortunately, I do not have time to dive into this.

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
