### ISSUE TITLE
Method not found: 'System.String Elasticsearch.Net.ElasticsearchSerializerExtensions.SerializeToString(Elasticsearch.Net.IElasticsearchSerializer, !!0, Elasticsearch.Net.SerializationFormatting)'.

### ISSUE THREAD

**Issue by mmisztal1980** [serilog/serilog-sinks-elasticsearch#246]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
- Serilog.Sinks.Elasticsearch v7.1.0
- Serilog.Sinks.Async v1.3.0
- Elasticsearch.Net v7.0.0-alpha2

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
No logs are being emitted into Elasticsearch v7.0.1. Enabling selflog yields the following exception:
```
Serilog.Sinks.Async.BackgroundWorkerSink fatal error in worker thread: System.MissingMethodException: Method not found: 'System.String Elasticsearch.Net.ElasticsearchSerializerExtensions.SerializeToString(Elasticsearch.Net.IElasticsearchSerializer, !!0, Elasticsearch.Net.SerializationFormatting)'.
   at Serilog.Sinks.Elasticsearch.ElasticsearchJsonFormatter.WriteLiteralValue(Object value, TextWriter output)
   at Serilog.Sinks.Elasticsearch.DefaultJsonFormatter.WriteLiteral(Object value, TextWriter output, Boolean forceQuotation)
   at Serilog.Sinks.Elasticsearch.DefaultJsonFormatter.WriteLiteral(Object value, TextWriter output, Boolean forceQuotation)
   at Serilog.Sinks.Elasticsearch.DefaultJsonFormatter.WriteJsonProperty(String name, Object value, String& precedingDelimiter, TextWriter output)
   at Serilog.Sinks.Elasticsearch.DefaultJsonFormatter.WritePropertiesValues(IReadOnlyDictionary`2 properties, TextWriter output)
   at Serilog.Sinks.Elasticsearch.ElasticsearchJsonFormatter.WriteProperties(IReadOnlyDictionary`2 properties, TextWriter output)
   at Serilog.Sinks.Elasticsearch.DefaultJsonFormatter.Format(LogEvent logEvent, TextWriter output)
   at Serilog.Sinks.File.FileSink.Serilog.Sinks.File.IFileSink.EmitOrOverflow(LogEvent logEvent)
   at Serilog.Sinks.File.FileSink.Emit(LogEvent logEvent)
   at Serilog.Sinks.RollingFile.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Sinks.Async.BackgroundWorkerSink.Pump()
```

**Please describe the expected behavior?**
Log messages emitted into elasticsearch

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**
- Install the Nuget packages listed above
- Configure serilog to target ES 7.0.1
- Configure serilog to use the  Elasticsearch sink though an Async sin
- Enable SelfLog
- Attempt to write log messages

**Comment by vhatsura** [comment]
Hey, @mmisztal1980 .
I'm afraid of you're using not compatible version of `ElasticSearch.Net`. In `7.1.0-alpha1` version was changed signature of `[SerializeToStringMethod`](https://github.com/elastic/elasticsearch-net/blob/dec4e1ec56b76d51bfecd36887f25eb08fd2d119/src/Elasticsearch.Net/Serialization/IElasticsearchSerializer.cs#L42)
@mivano, what do you think about it? As additional parameter is optional, we can use named parameter for formatting and this will fix the issue.

**Comment by mmisztal1980** [comment]
Hey @vhatsura and @mivano is there any temporary workaround that you can suggest for local use  until you guys support ES v7 ?

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
