### ISSUE TITLE
Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by naymore** [serilog/serilog-sinks-elasticsearch#250]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
7.1.0
7.2.0-alpha0005

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 2.0

**What is the target elasticsearch version?**
- elasticsearch v7.1.1 (offical docker image)

**Please describe the current behavior?**
I cannot log any messages - it doesn't even create an index.  
And I couldn't get any error details out of the serilog sink - or I didn't know where to look. 

```
.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
                {
                    AutoRegisterTemplate = true,
                    AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6,
                    IndexFormat = "my-test-index-{0:yyyy.MM}",
                    FailureCallback = e => Console.WriteLine("Unable to submit event " + e.MessageTemplate),
                    EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog |
                                       EmitEventFailureHandling.WriteToFailureSink |
                                       EmitEventFailureHandling.RaiseCallback,
                    FailureSink = new FileSink("./failures.txt", new JsonFormatter(), null)
                })
```

This doesn't contain any hints **WHY** it cannot ship any logs.

Anyway elasticsearch says...
```
{"type": "server", "timestamp": "2019-06-16T10:40:23,162+0000", "level": "DEBUG", "component": "o.e.a.a.i.t.p.TransportPutIndexTemplateAction", "cluster.name": "docker-cluster", "node.name": "c9c17f261cac", "cluster.uuid": "yRz-OC1UQGe83L_JbN_CnQ", "node.id": "-QG7I9-kQw-ghg9MAirUpQ",  "message": "failed to put template [serilog-events-template]" ,
"stacktrace": ["org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{numerics_in_fields={match_pattern=regex, path_match=fields\\.[\\d+]$, mapping={norms=false, index=true, type=text}}}, {string_fields={mapping={norms=false, index=true, type=text, fields={raw={ignore_above=256, index=true, type=keyword}}}, match_mapping_type=string, match=*}}], properties={message={index=true, type=text}, exceptions={type=nested, properties={ExceptionMessage={type=object, properties={MemberType={type=integer}}}, StackTraceString={index=true, type=text}, HResult={type=integer}, RemoteStackTraceString={index=true, type=text}, RemoteStackIndex={type=integer}, Depth={type=integer}}}}}]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:394) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.validateAndAddTemplate(MetaDataIndexTemplateService.java:253) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.access$300(MetaDataIndexTemplateService.java:65) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$2.execute(MetaDataIndexTemplateService.java:176) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) [elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) [elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.1.1.jar:7.1.1]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:835) [?:?]",
"Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{numerics_in_fields={match_pattern=regex, path_match=fields\\.[\\d+]$, mapping={norms=false, index=true, type=text}}}, {string_fields={mapping={norms=false, index=true, type=text, fields={raw={ignore_above=256, index=true, type=keyword}}}, match_mapping_type=string, match=*}}], properties={message={index=true, type=text}, exceptions={type=nested, properties={ExceptionMessage={type=object, properties={MemberType={type=integer}}}, StackTraceString={index=true, type=text}, HResult={type=integer}, RemoteStackTraceString={index=true, type=text}, RemoteStackIndex={type=integer}, Depth={type=integer}}}}}]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:152) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:392) ~[elasticsearch-7.1.1.jar:7.1.1]",
"... 17 more"] }
```

**Please describe the expected behavior?**
Am I doing it wrong? The sink should create an index by itself, right?

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by ishrat-pge** [comment]
I am seeing the same issue..any luck ..?

**Comment by roymoran** [comment]
Also seeing this issue. Working with Elasticsearch 7.2 and Serilog.Sinks.ElasticSearch 7.1.0.

**Comment by roymoran** [comment]
Had some luck with updating `Serilog.Sinks.ElasticSearch` to version `7.2.0-alpha0005` and started seeing the problem described in issue #181.

Defining a `TypeName` as described in the comment from that thread helped resolve the issue. https://github.com/serilog/serilog-sinks-elasticsearch/issues/181#issuecomment-507215738

**Comment by mivano** [comment]
Could you try the latest 8 version of this sink? It is an alpha package for now.

**Comment by SonOfSardaar** [comment]
Should i be expecting this issue in 8.0.1 ?

**Comment by mivano** [comment]
Old issue, cleaning up. Still facing this issue, feel free to reopen.
