### ISSUE TITLE
You'll need to index some data into Elasticsearch before you can create an index pattern

### ISSUE THREAD

**Issue by Venkateshjsoft** [serilog/serilog-sinks-elasticsearch#258]
I installed elasticsearch and kibana. I logged some test message using serilog. I see buffer file is created, but I have no clue why kibana says need some data. How data can be pulled from my local log path. Need advice

**Comment by mivano** [comment]
if only the buffer is created and filled, then it means the data is not send to the ES instance. Try it without the buffer and check the serilog selflog functionality. Maybe the sink cannot reach your ES instance.

**Comment by mivano** [comment]
Any luck? Closing this for now, but feel free to reopen.

**Comment by Venkateshjsoft** [comment]
Please find the error I received from selflog.
2019-08-04T07:48:58.6641062Z Exception while emitting periodic batch from Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper: System.MissingMethodException: Method not found: '!!0 Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAll(System.String, Elasticsearch.Net.PostData, Elasticsearch.Net.PutIndexTemplateRequestParameters)'.
   at Serilog.Sinks.Elasticsearch.ElasticsearchSinkState.RegisterTemplateIfNeeded()
   at Serilog.Sinks.Elasticsearch.Durable.ElasticsearchLogShipper.<OnTick>d__3.MoveNext()
