### ISSUE TITLE
Elasticsearch.Net.Utf8Json.JsonParsingException

### ISSUE THREAD

**Issue by jpseini** [serilog/serilog-sinks-elasticsearch#276]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [X] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.** 8.0.0 

**What is the target framework and operating system?** 

Should this work with netCore 3.0?

- [X] netCore 3.0 (preview-6) 
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
When trying to log into ES, the below exception is thrown.

> Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'{', actual:'<', at offset:0 ---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'{', actual:'<', at offset:0
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadIsBeginObjectWithVerify()
   at Elasticsearch.Net.Utf8Json.Formatters.DictionaryFormatterBase`5.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.DynamicDictionaryFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.LowLevelRequestResponseSerializer.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetSpecialTypes[TResponse](Byte[] bytes, IMemoryStreamFactory memoryStreamFactory, TResponse& cs)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)

I'm assuming the root cause of the issue is the sink, which is causing ElasticSearch.Net to throw the exception, but I could be mistaken.

I've configured CreateHostBuild method as follows:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .UseSerilog((ctx, config) =>
            {
                Serilog.Debugging.SelfLog.Enable(e => Console.WriteLine(e));
                config
                    .MinimumLevel.Information()
                    .Enrich.FromLogContext()
                    .Enrich.WithProperty("Application", "PlayPen")
                    .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200/"))
                    {
                        AutoRegisterTemplate = true,
                        AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv7,
                        //FailureCallback = (e) => {
                        //    Console.WriteLine($"Unable to submit event {e.MessageTemplate} and exception {e.Exception}");
                        //},
                        EmitEventFailure = EmitEventFailureHandling.WriteToSelfLog |
                                       EmitEventFailureHandling.WriteToFailureSink |
                                       EmitEventFailureHandling.RaiseCallback
                    })
                    .WriteTo.Debug();
            })
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
```

In the controller, I've tried sending just a plain string (as well as an object), with the same above exception:

`_logger.LogWarning("This is a warning message");`

Any insight as to what could be causing this? .netCore 3? have I misconfigured something? Or is the issue potentially with Elasticsearch.Net and the root cause is not the sink?

**Please describe the expected behavior?**
No exception and log is sent to ES.

**Comment by jpseini** [comment]
Does seem to be related to .net Core 3. Tested with a .net Core 2.2 project, with the same error message.

**Comment by ffMathy** [comment]
Version 8 is pretty broken of this NuGet package. Unfortunately, it is needed for Elasticsearch 7 support.

**Comment by hammadbinarif** [comment]
Gettting same error for .net framework 4.7.2, 
Serilog.Sinks.ElasticSearch 8.0.1
ElasticSearch 7.3

**Comment by renagaev** [comment]
same error

**Comment by md-fi** [comment]
I've just had this exception and it turned out to be the company proxy getting in the way and returning a html response instead of the json response from ES.

To fix it, I've disabled proxy detection in the sink options as follows:
```
var options = new ElasticsearchSinkOptions
{
    ...,
    ModifyConnectionSettings = x => x.DisableAutomaticProxyDetection()
};
```

**Comment by mivano** [comment]
Thanks for the feedback, hope it helps others.
