### ISSUE TITLE
Version 8.1 does NOT work with netCore 3.1 and ElasticSearch 6

### ISSUE THREAD

**Issue by minhhut** [serilog/serilog-sinks-elasticsearch#335]
**Does this issue relate to a new *feature* or an existing *bug*?**
- [x] Bug
- [ ] New Feature

**What version of Serilog.Sinks.Elasticsearch is affected?  Please list the related NuGet package.**
- Serilog.Sinks.ElasticSearch 8.1.0
- Serilog.AspNetCore 3.2.0

**What is the target framework and operating system? See [target frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) & [net standard matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).**

- [x] netCore 3.1
- [ ] netCore 2.0
- [ ] netCore 1.0
- [ ] 4.7
- [ ] 4.6.x
- [ ] 4.5.x

**Please describe the current behavior?**
- Works as expected with version 8.0 and ElasticSearch 6
- After upgraded to version 8.1, there are no error logs but no logs in ElasticSearch 6

**Please describe the expected behavior?**
- Version 8.1 should work with ElasticSearch 6

**If the current behavior is a bug, please provide the steps to reproduce the issue and if possible a minimal demo of the problem**

**Comment by mivano** [comment]
Can you enable the serilog selflog and see what it reports?

**Comment by minhhut** [comment]
I could see logs from Console or Debug. Do i need to try with Selflog?

**Comment by mivano** [comment]
Please do try, this will show issues with specific sinks

**Comment by minhhut** [comment]
Selflog doesn't help. 
- Version 8.0.1 and wrong connection string, still nothing in Selflog. 
- Version 8.01. and right connection, see result in ES
- Version 8.1.0, right + wrong connection, see nothing in ES

Here is how i config Serilog with AspNetCore 3.1 
```C#
Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
        .UseSerilog((ctx, config) => { ConfigSerilog(config, ctx); });

private static void ConfigSerilog(LoggerConfiguration loggerConfiguration, HostBuilderContext ctx)
{
	loggerConfiguration.ReadFrom.Configuration(ctx.Configuration)
		.Enrich.FromLogContext()
		.Enrich.WithExceptionDetails()
		.WriteTo.Console()
		.WriteTo.Elasticsearch(ConfigureElasticSink(ctx.Configuration));
}

private static ElasticsearchSinkOptions ConfigureElasticSink(IConfiguration configuration)
{
	var uri = new Uri(configuration["ElasticConfiguration:Uri"]);
	var options = new ElasticsearchSinkOptions(uri)
	{
		AutoRegisterTemplate = true,
		IndexFormat = $"logstash-{DateTime.UtcNow:yyyy-MM}",
		AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv6
	};

	if (!configuration["ElasticConfiguration:AwsRegion"].IsNullOrEmpty())
	{
		options.ModifyConnectionSettings = connection => ConfigureElasticProduction(configuration, uri);
	}
	return options;
}
```

**Comment by mivano** [comment]
Where did you configure the selflog here? (https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics)

**Comment by minhhut** [comment]
Thanks for the hints, i got the Selflog works now. With wrong connection string, i got error logs but with correct one still see nothing from Selflog. Could it be problem with ElasticSearch server? It work with version 8.0.1 but not 8.1.0

Error when wrong connection
```
2020-05-26T12:26:53.0989075Z Caught exception while preforming bulk operation to Elasticsearch: Elasticsearch.Net.ElasticsearchClientException: No such host is known.. Call: Status code unknown from: POST /_bulk
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.Bulk[TResponse](PostData body, BulkRequestParameters requestParameters)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatchChecked[T](IEnumerable`1 events)
   at Serilog.Sinks.Elasticsearch.ElasticsearchSink.EmitBatch(IEnumerable`1 events)
```

**Comment by mivano** [comment]
Then it looks like it can connect and send data. Can you look at the log file of ES itself? It keeps a rolling log on its server, it might indicate if it is actually receiving data.

**Comment by minhhut** [comment]
Unfortunately i don't have permission to access to that ES server, but i tried to test with ELK 6 on my local and version 8.1.0, it works fine. So i will close this issue.

**Comment by mivano** [comment]
That makes it harder to find out the issue. Let us know when you found the solution, curious to hear what it was.

**Comment by minhhut** [comment]
Found this log when using log4stash with our "problem" server, I don't know if this would give you more info

`log4net:ERROR Got error while reading response from ElasticSearch
System.InvalidOperationException: Some error occurred while sending request to ElasticSearch.
Got non ok status code: BadRequest.{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;21: type is missing;22: type is missing;23: type is missing;24: type is missing;25: type is missing;26: type is missing;27: type is missing;28: type is missing;29: type is missing;30: type is missing;31: type is missing;32: type is missing;33: type is missing;34: type is missing;35: type is missing;36: type is missing;37: type is missing;38: type is missing;39: type is missing;40: type is missing;41: type is missing;42: type is missing;43: type is missing;44: type is missing;45: type is missing;46: type is missing;47: type is missing;48: type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: type is missing;2: type is missing;3: type is missing;4: type is missing;5: type is missing;6: type is missing;7: type is missing;8: type is missing;9: type is missing;10: type is missing;11: type is missing;12: type is missing;13: type is missing;14: type is missing;15: type is missing;16: type is missing;17: type is missing;18: type is missing;19: type is missing;20: type is missing;21: type is missing;22: type is missing;23: type is missing;24: type is missing;25: type is missing;26: type is missing;27: type is missing;28: type is missing;29: type is missing;30: type is missing;31: type is missing;32: type is missing;33: type is missing;34: type is missing;35: type is missing;36: type is missing;37: type is missing;38: type is missing;39: type is missing;40: type is missing;41: type is missing;42: type is missing;43: type is missing;44: type is missing;45: type is missing;46: type is missing;47: type is missing;48: type is missing;"},"status":400}
   at log4stash.ElasticClient.ResponseValidator.CheckResponse(IRestResponse response)
   at log4stash.ElasticClient.ResponseValidator.ValidateResponse(IRestResponse response)
   at log4stash.WebElasticClient.SafeSendRequestAsync(IRestRequest request)`

**Comment by mivano** [comment]
Not sure what it is, but at least it is with ES. Maybe try at the Elastic issue list?

**Comment by minhhut** [comment]
log4stash at lease gave some error/hints. I think it would be nice if serilog does as well instead of showing nothing

**Comment by mivano** [comment]
Totally agree. You should see something with the selflog at least. Although a not working sinks should not block your application.
